package enumerators;

public enum WeekEnum { // ## FUNCIONA COMO UMA CONSTANTE, NÃO PODE TER SEU VALOR ALTERADO ## //
        DOMINGO, SEGUNDA, TERÇA, QUARTA, QUINTA, SEXTA, SÁBADAO; // ## SEMPRE DECLARA COMO CONSTANTE, EM BAIXA ALTA ## //

}
